trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    make test-app
  displayName: 'Test and coverage'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar-source'
    organization: 'esgeronimo-github'
    scannerMode: 'CLI'
    configMode: 'file'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- script: |
    make build-app VERSION=$(build.buildId)
  displayName: 'Build image'
