trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar-source'
    organization: 'esgeronimo-github'
    scannerMode: 'CLI'
    configMode: 'file'
- script: |
    make build_app VERSION=$(build.buildId)
  displayName: 'Build image'
