apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-book
  labels:
    app: address-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-book
  template:
    metadata:
      labels:
        app: address-book
    spec:
      containers:
        - name: address-book
          image: esgeronimo/address-book:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          resources:
           limits:
             memory: 256Mi
             cpu: "1"
           requests:
             memory: 128Mi
             cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.serviceName }}"
spec:
  selector:
    app: address-book
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080