CREATE TABLE ADDRESS_BOOK (
    PR_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID VARCHAR(36) UNIQUE NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP   
)