CREATE TABLE IF NOT EXISTS ADDRESS_BOOK (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UUID VARCHAR(36) UNIQUE NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP   
);

CREATE TABLE IF NOT EXISTS CONTACT (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UUID VARCHAR(36) UNIQUE NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS_BOOK_ID VARCHAR(36) NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ADDRESS_BOOK_ID) REFERENCES ADDRESS_BOOK(UUID)
);